# Nombre del workflow (aparecerá en la GUI)
name: production
# Cuándo se ejecuta: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on: push
# Listado de jobs
jobs:
  # ID del job. Cada job se ejecuta en una máquina nueva
  my-job:
    # Tipo de máquina. Puede ser de Github o un self-hosted runner:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest
    steps:
      # Checkout del código
      - uses: actions/checkout@v3
      # Instalar go
      - uses: actions/setup-go@v3
      # Docker build
      - name: Docker build
        run: docker build . --file Dockerfile --tag hi-application:v1
      # Execute tests
      - name: Execute tests
        run: docker run -d hi-application:v1 go test ./...
